version: '3.8'
services:
  app:
    image: test
    ports:
      - "1080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always