version: '3.8'
services:
  app:
    image: ${DOCKER_USERNAME}/validate-image:latest
    ports:
      - "1080:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"