name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Create .env file
      run: |
        echo "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}" >> .env
        echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}" >> .env
        echo "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}" >> .env
        echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env

    - name: Build Docker image
      run: |
        docker build --build-arg ENV_FILE=.env -t bestbest/be-validate-image .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag bestbest/be-validate-image bestbest/be-validate-image:v1.0.2
        docker push bestbest/be-validate-image:v1.0.2

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker rm -f be-validate-image || true
          docker pull bestbest/be-validate-image:v1.0.2
          
          # Run container with network host and environment variables
          docker run -d --name be-validate-image \
            --network host \
            -p 1080:8000 \
            bestbest/be-validate-image:v1.0.2
          
          # Check if container is running
          if ! docker ps | grep -q be-validate-image; then
            echo "Container failed to start. Checking logs:"
            docker logs be-validate-image
            exit 1
          fi
          
          # Wait for application to initialize
          sleep 10
          
          # Start Celery worker with non-root user
          docker exec -d -u appuser be-validate-image celery -A utils.celery_app worker --loglevel=info
          
          # Verify Celery worker
          sleep 5
          if ! docker exec be-validate-image ps aux | grep -q "[c]elery worker"; then
            echo "Celery worker failed to start. Checking logs:"
            docker logs be-validate-image
            exit 1
          fi
          
          echo "Deployment completed successfully"
          
          # Check logs for any errors
          docker logs be-validate-image | grep -i error || true