name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/validate-image:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/validate-image:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/where-my-images/app
          cat > docker-compose.yml << 'EOL'
          version: '3.8'
          services:
            app:
              image: ${{ secrets.DOCKER_USERNAME }}/validate-image:latest
              ports:
                - "1080:8000"
              depends_on:
                - redis
              environment:
                - REDIS_HOST=redis
                - REDIS_PORT=6379
              restart: always

            redis:
              image: redis:latest
              ports:
                - "6379:6379"
              restart: always
          EOL
          docker compose pull
          docker compose down
          docker compose up -d
        timeout: 600s