name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t bestbest/be-validate-image .

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag bestbest/be-validate-image ${{ secrets.DOCKER_USERNAME }}/bestbest/be-validate-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/bestbest/be-validate-image:latest

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker rm -f be-validate-image || true
          docker pull bestbest/be-validate-image:v1.0.0
          docker pull bestbest/be-validate-image:v1.0.0
          docker stop bestbest/be-validate-image || true
          docker rm bestbest/be-validate-image || true
          docker run -d --name be-validate-image -p 1080:8000 bestbest/be-validate-image:v1.0.0